version: "3.7"
services:
  app:
    container_name: pcc_app
    build:
      dockerfile: ./Dockerfile
      context: ./containers/app/
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./app/:/var/www
    networks:
      - pcc-dev

networks:
  pcc-dev:
    driver: bridge